### ISSUE TITLE
acc to tax

### ISSUE THREAD

**Issue by pcantalupo** [darcyabjones/gi-to-tax#4]
Hello,

As you might know NCBI is [phasing out GI values](http://www.ncbi.nlm.nih.gov/news/03-02-2016-phase-out-of-GI-numbers/). Are you planning on writing acc-to-tax code? Thank you,

Paul

**Comment by darcyabjones** [comment]
Thanks, I did know about this but haven't yet had the time to look at it properly.
I'm hoping to add that functionality before they completely remove gi support, as well as a few performance updates and unit tests.

You are more than welcome to submit pull requests too if you are so inclined :)
